name: CI Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      publish_job:
        description: "Choose which publish job to run"
        required: true
        default: "beta"
        type: choice
        options:
          - beta
          - production

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      # Build the project before publishing
      - name: Build the project
        run: npm run build

  publish-beta:
    needs: install-and-build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.publish_job == 'beta' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Set npm registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # First publish using the name from package.json
      - name: Publish beta version
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Modify package.json to publish under "inputron"
      - name: Temporarily change package name to "inputron"
        run: |
          sed -i 's/"name": "[^"]*"/"name": "inputron"/' package.json

      # Second publish under the name "inputron"
      - name: Publish under "inputron"
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Revert the package.json back to original name
      - name: Revert package.json changes
        run: git checkout package.json

  publish-production:
    needs: install-and-build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.publish_job == 'production' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Set npm registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # First publish using the name from package.json
      - name: Publish production version
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Modify package.json to publish under "inputron"
      - name: Temporarily change package name to "inputron"
        run: |
          sed -i 's/"name": "[^"]*"/"name": "inputron"/' package.json

      # Second publish under the name "inputron"
      - name: Publish under "inputron"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Revert the package.json back to original name
      - name: Revert package.json changes
        run: git checkout package.json
