name: CI Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      publish_job:
        description: "Choose which publish job to run"
        required: true
        default: "beta"
        type: choice
        options:
          - beta
          - production

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Caching node_modules for faster installs
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      # Caching build artifacts and ensuring 'dist/' is cached
      - name: Cache build artifacts
        id: build-cache
        uses: actions/cache@v2
        with:
          path: |
            build/
            dist/
          key: ${{ runner.os }}-build-${{ hashFiles('src/**/*') }} # Include source files in hash to invalidate on change
          restore-keys: |
            ${{ runner.os }}-build-

      # Run the build command, which should generate 'dist/'
      - name: Build the project
        run: npm run build

  test:
    needs: install-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use cached node_modules and build
        run: npm run test

  publish-beta:
    needs: [install-and-build, test]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.publish_job == 'beta' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Ensure 'dist/' is present before publishing
      - name: Verify dist folder
        run: ls -la dist

      - name: Set npm registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Append commit SHA to version for beta
        run: |
          GIT_COMMIT_HASH=$(git rev-parse --short HEAD)
          npm version $(node -p "require('./package.json').version + '-beta.${GIT_COMMIT_HASH}'") --no-git-tag-version

      # Ensure build artifacts (dist) are published
      - name: Use cached build
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-production:
    needs: [install-and-build, test]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.publish_job == 'production' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Ensure 'dist/' is present before publishing
      - name: Verify dist folder
        run: ls -la dist

      - name: Set npm registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Use cached build
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
